config/routes.rb
Nfl::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}
                     
  resources :nfl_players
  
  resources :polls do
    get 'page/:page', :action => :index, :on => :collection
    get :user_results
  end
  
  resources :poll_options do
    get :vote_up
    get :unvote
    get :display_stats
  end

  root :to => "polls#vote"

  match "player_names" => "nfl_players#player_names", :as => :player_names
  match "my_polls" => "polls#my_polls", :as => :my_polls
  match "my_votes" => "polls#my_votes", :as => :my_votes
  match "leaderboard" => "polls#leaderboard", :as => :leaderboard

  match "incoming_mail" => "mailgun#incoming_mail"

  match "about" => "info#about", :as => :about
  match "tos" => "info#tos", :as => :tos
  match "privacy" => "info#privacy", :as => :privacy
  match "contact" => "info#contact", :as => :contact
  
    

end

app/models/poll.rb
class Poll
  include Mongoid::Document
  include Mongoid::Timestamps
  
  belongs_to :user
  has_many :poll_options, :dependent => :destroy
  accepts_nested_attributes_for :poll_options, :allow_destroy => true, :reject_if => :all_blank
  attr_accessible :poll_options_attributes, :question, :week, :scoring, :note, :votes, :max_vote_options, :user_votes, :user, :subtitle
  validate :valid_poll
  validates :note, :length => {:maximum => 240}
  
  scope :week, ->(week){ where(week: week)}
    
  QUESTION_TYPES = ["Who should I start?",
                    "Who should I pick up?"]
                   
  SCORING_TYPES = ["Traditional",
                  "Performance",
                  "PPR"]
  
  field :question,          type: String
  field :subtitle,          type: String
  field :week,              type: Integer, default: DateHelper::get_week(Time.now)
  field :scoring,           type: String 
  field :note,              type: String
  #field :votes,             type: Integer, default: 0
  field :max_vote_options,  type: Integer, default: 1
  #field :user_votes,        type: Hash, default: {}
  field :expired,           type: Boolean
  
  def total_votes
    v = 0
    self.poll_options.each do |poll_option|
      v += poll_option.users.count
    end
    return v
  end
    
  def user_total_votes(user)
    v = 0
    self.poll_options.each do |poll_option|
      v += 1 if poll_option.voted?(user)
    end
    return v
  end
  
  def user_votes_left(user)
    self.max_vote_options - self.user_total_votes(user)
  end
  
  def can_vote?(user)
    self.max_vote_options - self.user_total_votes(user) > 0
  end  
  
  def voted?(user)
    self.user_votes_left(user) == 0
  end
  
  def editable?
    return self.total_votes == 0 && !self.expired?
  end
  
  def expired?
    if DateHelper::get_week(Time.now) > self.week
      self.expired = true
    end
    self.poll_options.each do |poll_option|
      self.expired = true if poll_option.expired?      
    end
    self.save
    self.expired
  end
  
  private
    def valid_poll
      if self.poll_options.length < 2
        errors[:valid_poll]= "You must provide at least 2 players."
      end
      if self.poll_options.length <= self.max_vote_options
        errors[:valid_poll]= "You must have less choices (#{self.poll_options.length}) than possible options (#{max_vote_options})."
      end
    end

    
  
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show, :vote]
  
  def index
    @polls = Poll.desc(:created_at).page(params[:page]).per(3)
  end

  def my_polls
    @polls = Poll.where(:user => current_user).desc(:created_at)
  end
  
  def my_votes
    if params[:week]
      @week = params[:week].to_i
    else
      #default to get last weeks data
      @week = DateHelper::get_week(Time.now) - 1
    end
    @polls = current_user.polls_voted(@week)
    @polls.sort{ |x,y| x.created_at <=> y.created_at} if !@poll.nil?
    #.sort { |d| d.created_at}
  end
      
  def my_profile
  end
  
  
  def leaderboard
    @users = User.desc(:points)
  end

  def show
    @poll = Poll.find(params[:id])
  end

  def vote
    polls = Poll.excludes(:user => current_user).desc(:created_at).to_a
    while !polls.empty? && @poll.nil?
      poll = polls.pop
      @poll = poll if (poll && !poll.voted?(current_user) && !poll.expired?)
    end
  
    @last_poll = Poll.find(session[:last_poll]) if session[:last_poll]
      
  end

  def new
    @poll = Poll.new
    5.times {@poll.poll_options.build}
  end

  def edit
    @poll = Poll.find(params[:id])
    (5 - @poll.poll_options.count).times {@poll.poll_options.build}
    
  end

  def create
    @poll = Poll.new(params[:poll])
    @poll.user_id = current_user.id


    if @poll.save
      redirect_to polls_path, notice: 'Poll was successfully created.' 
    else
      if params[:poll][:poll_options_attributes]
        params[:poll][:poll_options_attributes].to_a.flatten.count({"name"=>""}).times {@poll.poll_options.build}
      end
      render action: "new" 
    end
  end

  def update
    @poll = Poll.find(params[:id])

    if @poll.update_attributes(params[:poll])
      redirect_to polls_path, notice: 'Poll was successfully created.' 
    else
      render action: "edit" 
    end
  end

  def destroy
    @poll = Poll.find(params[:id])
    @poll.destroy

    redirect_to polls_path
  end
  
  
  def user_results
    @poll = Poll.find(params[:poll_id])
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/views/polls/_form.html.haml
= form_for(@poll) do |f| 
  =if @poll.errors.any?
    %h3
      = pluralize(@poll.errors.count, "error")
      prohibited this poll from being saved:
    %ul
      - @poll.errors.full_messages.each do |msg| 
        %li
          = msg
  .row
    .span3
      = f.label :question, "Question"
      = f.collection_select :question, Poll::QUESTION_TYPES, :to_s, :to_s
      %p
      = f.label :subtitle, "Subtitle"
      = f.text_field :subtitle
      %p
      = f.label :week, "Week \#"
      = f.collection_select :week, 1..17, :to_i, :to_i
      %p
      = f.label :max_vote_options, "Max Players to Vote For"
      = f.collection_select :max_vote_options, 1..5, :to_i, :to_i
      %p
      = f.label :scoring, "Scoring Type"
      = f.collection_select :scoring, Poll::SCORING_TYPES, :to_s, :to_s
      
    .span3
      Enter up to 5 players:
      <p><p>
      = f.fields_for :poll_options do |builder|
        = render 'poll_options_fields', f:builder
        <p>
    .span3
      = f.label :note, "Notes, up to 240 characters"
      = f.text_area :note, :rows => 10, :style => "width:400px"
  %br
  %br
  = f.submit "Create Poll", :class => "btn btn-primary btn-large"
  

app/views/polls/_how_it_works.haml
.span3.pane.minor-pane
  .row-fluid
    %h1 How It Works:
  .row-fluid
    .span7.floatleft
      %p
      1. Login With Facebook
      %br
      2. Create a Poll
      %br
      3. Vote on Questions
      %br
      4. Raise Fantasy IQ (FIQ)
      %br
      5. Share With Friends
      %br
      6. Win Prizes
      %br
      .spacing
      =image_tag("fb-button.png", :width => "200px")
      %br
      %br
      %p
      = link_to "Sign in", new_user_session_path
      or
      = link_to "Sign up", new_user_registration_path
    / /span
    .span4.floatleft
    / /span
  / /row-fluid
/ /span

app/views/polls/_info.html.haml
.container-full
  .container-fluid
    .row-fluid
      %h1
        %span.fan FAN
        %span.sensus SENSUS
      %h2 Fantasy Football question? -- Get the fan consensus with Fansensus
      .item
        =image_tag("fs-choices.png", :style => "width: 90%")
        %h4 Answer Questions
        %p Fansensus makes it fast and easy for you to help out other fantasy sports players.  Answer correctly to raise your Fantasy IQ (FIQ) and win prizes.
      .item
        =image_tag("fs-questionmark.png", :style => "width: 90%")
        %h4 Create Polls
        %p Sign up to create your own poll questions.  Get advice from other players who aren't in your league.  We don't spam and it's free!
      .item
        =image_tag("fs-stats.png", :style => "width: 90%")
        %h4 Track Results
        %p See how people voted.  Fansensus will track everyone's historical accuracy to help you make the best educated decision.
 

app/views/polls/_poll_show_form.html.haml
.poll-pane.span6.pane{:id => "#{poll._id}"}
  .row-fluid
    %h1=poll.question
    - if poll.user == current_user
      -if poll.editable?
        = link_to '<i class="icon-pencil">Edit</i>'.html_safe, edit_poll_path(poll), class:"edit_poll"
        =button_to "Delete", poll, {:method => :delete, :confirm => "Are you sure?",
                   :class => "btn btn-danger btn-mini"}
    %h3.header-topright
      -if poll.user.image
        =image_tag(poll.user.image)
      &nbsp;
      =poll.user.display_name
    .row-fluid
      .floatleft
        %h2 
          Week
          =poll.week
          \:
          =poll.subtitle
        %h2
          Scoring:
          =poll.scoring
      .floatright
        %h4
          <br>             
          - if poll.expired?
            This poll has expired.
          - else
            - if poll.user_votes_left(current_user) > 0            
              Choose
              =poll.user_votes_left(current_user)
              more.
            - else
              Thanks for voting!
    .row-fluid
      .spacing
      %table.table.polltable
        %colgroup
          %col
          %col
          %col
          %col
        %thead
          %th &nbsp;
          %th Player
          %th VS
          %th Game
        %tbody
        - poll.poll_options.each_with_index do |poll_option, index|
          - letter = index.to_s(27).tr("0-9a-q", "A-Z")
          %tr.poll-row
            %td   
              -if !poll.expired?
                -if poll_option.can_vote?(current_user)
                  -if user_signed_in?
                    =link_to letter, poll_option_vote_up_path(poll_option), :remote => true, 
                                   :class =>"btn poll-btn btn-large btn-primary", :id => poll_option._id
                  -else
                    =link_to letter, new_user_registration_path,
                                   :class =>"btn poll-btn btn-large btn-primary", :id => poll_option._id
                -else
                  -if poll_option.voted?(current_user)
                    =link_to '<i class="icon-ok"></i>'.html_safe,
                              poll_option_unvote_path(poll_option), :remote => true, 
                              :class =>"btn poll-btn btn-large btn-warning", :id => poll_option._id
            %td{:overflow => "hidden"}
              -if !poll_option.nfl_player.nil?
                =link_to poll_option.nfl_player.name_team_pos,
                         poll_option_display_stats_path(poll_option), 
                        :id => poll_option._id, :remote => true
              -else
                =poll_option.name
                
            %td
              -if !poll_option.nfl_player.nil? 
                =poll_option.nfl_player.opp
            %td
              -if !poll_option.nfl_player.nil? 
                =poll_option.nfl_player.game_time_formatted
    -if !poll.note.empty?
      .row-fluid
        %h2 Notes
        %p=poll.note          
    .row-fluid
      .pull-right
        Asked
        =time_ago_in_words(poll.created_at)
        ago.


        

app/views/polls/_view_poll.html.haml
/ -if poll.voted?(current_user) || poll.user == current_user
=render "polls/poll_show_form", :poll => poll
/ -else poll.can_vote?(current_user)
/   =render "polls/poll_vote", :poll => poll

app/views/polls/edit.html.haml
%h1==Editing poll

= render 'form' 

= link_to 'Show', @poll 
|
= link_to 'Back', polls_path 

app/views/polls/index.html.haml
.row.span12
  %h1 Listing polls
  =link_to 'Create New Poll', new_poll_path, :class => "btn btn-large"
  <br><br>
-@polls.each do |poll|
  =render "view_poll", :poll => poll
%p
%br
%br
= paginate @polls
      
.row

app/views/polls/leaderboard.html.haml
%h1 Leaderboard
%table.table.table-striped.table-bordered
  %thead
    %tr
      %th.center Rank
      %th.center Member
      %th.center Points
  -@users.each_with_index do |user, index|
    %tr
      %h3
        %td.center.mid
          =index+1
        %td.mid
          - if user.image
            =image_tag(user.image)
          - else
            =image_tag("image_missing.gif", :size => "50x50")
          =user.abbr_name
        %td.center.mid
          =user.fiq

app/views/polls/my_polls.html.haml
.span1
.poll-pane.span10.pane
  %h1 My Poll Results
-@polls.each do |poll|
  =render "polls/view_poll", :poll => poll
  =render "polls/results", {:poll => poll, :last_poll => true}

app/views/polls/my_votes.html.haml
.span1
.poll-pane.span10.pane
  Your current Fantasy IQ (FIQ):
  =current_user.fiq
  %p

  .navbar
    .navbar-inner2
      %ul.nav
        -(0..17).each do |week|
          - if week == @week 
            %li.active2
              - if week == 0 
                =link_to "All Weeks", my_votes_path(:week => week)
              - else
                =link_to week, my_votes_path(:week => week)
          - else 
            %li
              - if week == 0
                =link_to "All Weeks", my_votes_path(:week => week)
              - else
                =link_to week, my_votes_path(:week => week)
.row
-if @polls
  -@polls.each do |poll|
    - if poll 
      =render "polls/results", {:poll => poll, :last_poll => false}
  
  

app/views/polls/new.html.haml
%h1==New Poll
= params.inspect
= render 'form'

= link_to 'Back', polls_path

app/views/polls/show.html.haml
= render "polls/poll_show_form", {:poll => @poll}
.row
= link_to 'Back', my_votes_path 

app/views/polls/user_results.js.erb
$('#<%= "user_result_"+@poll._id.to_s %>').toggle();

app/views/polls/vote.html.haml
.row-fluid
  .span1
  -if @poll
    = render "polls/poll_show_form", {:poll => @poll}
    -if @last_poll
      = render "polls/results", {:poll => @last_poll, :last_poll => true }
    -else
      = render "polls/how_it_works"  
    
    =render "poll_options/stats", {:poll => @poll}                
  -else
    .poll-pane.span6.pane
      %h1 You have answered all the polls! <br>
      <br>
      =link_to 'Create New Poll', new_poll_path, :class => "btn btn-large"
  -if !user_signed_in?
    =render "polls/info"
      