config/routes.rb
Nfl::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}
                     
  resources :nfl_players
  
  resources :polls do
    get 'page/:page', :action => :index, :on => :collection
    get :user_results
  end
  
  resources :poll_options do
    get :vote_up
    get :unvote
    get :display_stats
  end

  root :to => "polls#vote"

  match "player_names" => "nfl_players#player_names", :as => :player_names
  match "my_polls" => "polls#my_polls", :as => :my_polls
  match "my_votes" => "polls#my_votes", :as => :my_votes
  match "leaderboard" => "polls#leaderboard", :as => :leaderboard

  match "incoming_mail" => "mailgun#incoming_mail"

  match "about" => "info#about", :as => :about
  match "tos" => "info#tos", :as => :tos
  match "privacy" => "info#privacy", :as => :privacy
  match "contact" => "info#contact", :as => :contact
  
    

end

app/models/nfl_player.rb
class NflPlayer
  include Mongoid::Document
  embeds_many :stats
  belongs_to :poll_option

  field :yahoo_id,  type: String 
  field :name,      type: String
  field :number,    type: String
  field :position,  type: String
  field :team,      type: String
  field :height,    type: String
  field :weight,    type: String
  field :age,       type: Integer
  field :born,      type: String
  field :college,   type: String
  field :draft,     type: String
  field :opp,       type: String
  field :season,    type: Integer
  field :game_time, type: Time
  field :_id,       type: String, default: ->{yahoo_id.to_s.parameterize}
  
  def to_json
    { "basic_data" => self.attributes    }
  end
  
  def name_team_pos
    self.name +
    " (" +
    self.team + 
    " - " +
    self.position + 
    ")"
  end
  
  def game_time_formatted
    if self.game_time
      self.game_time.localtime.strftime('%a %l:%M%P')
    end
  end
end

app/controllers/nfl_players_controller.rb
class NflPlayersController < ApplicationController
  # GET /nfl_players
  # GET /nfl_players.json
  def index
    # raise params.inspect
    @nfl_players = NflPlayer.all
    
    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @nfl_players }
    # end
  end

  # GET /nfl_players/1
  # GET /nfl_players/1.json
  def show
    @nfl_player = NflPlayer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { 
        render json: @nfl_player.to_json }
    end
  end

  # GET /nfl_players/new
  # GET /nfl_players/new.json
  def new
    @nfl_player = NflPlayer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nfl_player }
    end
  end

  # GET /nfl_players/1/edit
  def edit
    @nfl_player = NflPlayer.find(params[:id])
  end

  # POST /nfl_players
  # POST /nfl_players.json
  def create
    @nfl_player = NflPlayer.new(params[:nfl_player])

    respond_to do |format|
      if @nfl_player.save
        format.html { redirect_to @nfl_player, notice: 'Nfl player was successfully created.' }
        format.json { render json: @nfl_player, status: :created, location: @nfl_player }
      else
        format.html { render action: "new" }
        format.json { render json: @nfl_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nfl_players/1
  # PUT /nfl_players/1.json
  def update
    @nfl_player = NflPlayer.find(params[:id])

    respond_to do |format|
      if @nfl_player.update_attributes(params[:nfl_player])
        format.html { redirect_to @nfl_player, notice: 'Nfl player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nfl_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nfl_players/1
  # DELETE /nfl_players/1.json
  def destroy
    @nfl_player = NflPlayer.find(params[:id])
    @nfl_player.destroy

    respond_to do |format|
      format.html { redirect_to nfl_players_url }
      format.json { head :no_content }
    end
  end
  
  def player_names
    player_regex = Regexp.new(params[:term],true)
    @players = NflPlayer.asc(:name).where(name: player_regex)
    render json: @players.map(&:name_team_pos) 
  end
    
end

app/helpers/nfl_players_helper.rb
module NflPlayersHelper
  
  POS_HASH = {"Quarterback" => "QB",
              "Running Back" => "RB",
              "Wide Receiver" => "WR",
              "Tight End" => "TE",
              "Kicker" => "K",
              "Defensive End" => "DL",
              "Defensive Tackle" => "DL",
              "Nose Tackle" => "DL",
              "Cornerback" => "CB",
              "Linebacker" => "LB",
              "Safety" => "S"}
  
  TEAM_HASH = { "Arizona Cardinals" => "Ari",
                "Atlanta Falcons" => "Atl",
                "Baltimore Ravens" => "Bal",
                "Buffalo Bills" => "Buf",
                "Carolina Panthers" => "Car",
                "Chicago Bears" =>  "Chi",
                "Cincinnati Bengals" => "Cin",
                "Cleveland Browns" =>  "Cle",
                "Dallas Cowboys" => "Dal",
                "Denver Broncos" => "Den",
                "Detroit Lions" => "Det",
                "Green Bay Packers" => "GB",
                "Houston Texans" => "Hou",
                "Indianapolis Colts" => "Ind",
                "Jacksonville Jaguars" => "Jac",
                "Kansas City Chiefs" => "KC",
                "Miami Dolphins" => "Mia",
                "Minnesota Vikings" => "Min",
                "New England Patriots" => "NE",
                "New Orleans Saints" => "NO",
                "New York Giants" => "NYG",
                "New York Jets" => "NYJ",
                "Oakland Raiders" => "Oak",
                "Philadelphia Eagles" => "Phi",
                "Pittsburgh Steelers" => "Pit",
                "San Diego Chargers" => "SD",
                "San Francisco 49ers" => "SF",
                "Seattle Seahawks" => "Sea",
                "St. Louis Rams" => "StL",
                "Tampa Bay Buccaneers" => "TB",
                "Tennessee Titans" => "Ten",
                "Washington Redskins" => "Was"}            
              
  
  def NflPlayersHelper::position_abbr(pos)

    if POS_HASH[pos]
      POS_HASH[pos]
    else
     "No Position Error"
    end
  end
    
  def NflPlayersHelper::team_abbr(team)
     
    if TEAM_HASH[team]
      TEAM_HASH[team]
    else 
      if TEAM_HASH.invert[team]
        TEAM_HASH.invert[team]      
      else
        "No Team Error"
      end
    end
  end
end

app/views/nfl_players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nfl_players/edit.html.erb
<h1>Editing nfl_player</h1>

<%= render 'form' %>

<%= link_to 'Show', @nfl_player %> |
<%= link_to 'Back', nfl_players_path %>

app/views/nfl_players/index.html.haml
%h1
  Listing nfl_players

%table
  -@nfl_players.each do |nfl_player|
    %tr
      %td
        =link_to nfl_player.name, nfl_player_path(nfl_player)
        / =nfl_player.name

      %td
        =nfl_player.position
      %td
        =nfl_player.number

=link_to 'New Nfl player', new_nfl_player_path

app/views/nfl_players/new.html.erb
<h1>New nfl_player</h1>

<%= render 'form' %>

<%= link_to 'Back', nfl_players_path %>

app/views/nfl_players/show.html.haml
%p#notice
  = notice
  
%h3=@nfl_player.name 
%b==Yahoo_id: 
=@nfl_player.yahoo_id
%br
%b==Number: 
=@nfl_player.number   
%br
%b==Position: 
=@nfl_player.position
%br
%b==Team:     
=@nfl_player.team
%br
%b==Height:   
=@nfl_player.height   
%br
%b==Weight:
=@nfl_player.weight   
%br
%b==Age: 
=@nfl_player.age    
%br
%b==Born:
=@nfl_player.born     
%br
%b==College:
=@nfl_player.college  
%br
%b==Draft:
=@nfl_player.draft
%p

-if @nfl_player.stats[0].nil?
  %h3 No stats available for this player
-else
  %table.table.table-striped.table-bordered
    %thead
      %tr
        -@nfl_player.stats[0].stat_display_order.each do |label|
          %th
            =label
    %tbody
      -@nfl_player.stats.each do |stat|
        %tr  
        -stat.stat_display_order.each do |label|
          %td
            =stat[label]
        
        




 