config/routes.rb
Nfl::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}
                     
  resources :nfl_players
  
  resources :polls do
    get 'page/:page', :action => :index, :on => :collection
    get :user_results
  end
  
  resources :poll_options do
    get :vote_up
    get :unvote
    get :display_stats
  end

  root :to => "polls#vote"

  match "player_names" => "nfl_players#player_names", :as => :player_names
  match "my_polls" => "polls#my_polls", :as => :my_polls
  match "my_votes" => "polls#my_votes", :as => :my_votes
  match "leaderboard" => "polls#leaderboard", :as => :leaderboard

  match "incoming_mail" => "mailgun#incoming_mail"

  match "about" => "info#about", :as => :about
  match "tos" => "info#tos", :as => :tos
  match "privacy" => "info#privacy", :as => :privacy
  match "contact" => "info#contact", :as => :contact
  
    

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FanSensus | Get Consensus On Your Fantasy Sports Questions 
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}    
    = stylesheet_link_tag 'application'
    = csrf_meta_tag
    = javascript_include_tag "application"
    = google_webfonts_link_tag :michroma => [400]
    = yield :scripts
    %link{:href => "styles/bootstrap.css", :media => "screen", :rel => "stylesheet"}
    / Le HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    %script{:src => "vendor/jquery-1.7.2/jquery-1.7.2.js", :type => "text/javascript"}
    %script{:src => "vendor/bootstrap.js", :type => "text/javascript"}
    :javascript
      $(document).ready(function () {
      $("[rel=tooltip]").tooltip();
      });
%body
  .navbar.navbar-fixed-top
    .navbar-inner
      .container-fluid
        %a.btn.btn-navbar{:data => {:toggle => "collapse", :target=>".nav-collapse"}}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{:href => "/"} 
          %span.fan> Fan
          %span.sensus sens.us
        .btn-group.pull-right
          %a.btn.btn-primary.dropdown-toggle{:data => {:toggle=>"dropdown"}, :href=>"#"}
            - if user_signed_in?
              - if current_user.image
                = image_tag(current_user.image)
              = current_user.display_name
              %b.caret
            - else
              Sign in
          %ul.dropdown-menu
            - if user_signed_in?
              %li= link_to "My Profile", edit_user_registration_path
              %li= link_to "Edit Profile", edit_user_registration_path     
              %li.divider
              %li= link_to "Sign out", destroy_user_session_path         
            - else 
              %li= link_to "Sign in", new_user_session_path
              %li= link_to "Sign up", new_user_registration_path                         
        .nav-collapse
          %ul.nav
            %li= link_to "Create Poll", new_poll_path
            %li= link_to "My Polls", my_polls_path
            %li= link_to "My Votes", my_votes_path
            %li= link_to "Leaderboard", leaderboard_path
  .container-fluid{:style => "padding-top: 60px"}
    .row-fluid
      - if flash[:notice]
        .alert.alert-success
          = flash[:notice]
      - if flash[:error]
        .alert.alert-error
          = flash[:error]
      = yield
%footer{:style => "padding-top: 60px"}
  .navbar.navbar-fixed-bottom
    .navbar-inner
      .container-fluid
        %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{:href => "#"}
        .nav-collapse
          %ul.nav
            %li
              %p &copy; Fansensus 2012
            %li= link_to "About Us", about_path
            %li= link_to "Terms of Service", tos_path
            %li= link_to "Privacy Policy", privacy_path
            %li= link_to "Contact Us", contact_path